#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Oauth2Demo.Resource", IsApplication=true)]

namespace Oauth2Demo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::Oauth2Demo.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::Oauth2Demo.Resource.String.Hello;
			global::Xamarin.Auth.Resource.Animation.slide_in_right = global::Oauth2Demo.Resource.Animation.slide_in_right;
			global::Xamarin.Auth.Resource.Animation.slide_out_left = global::Oauth2Demo.Resource.Animation.slide_out_left;
			global::Xamarin.Auth.Resource.Drawable.ic_arrow_back = global::Oauth2Demo.Resource.Drawable.ic_arrow_back;
			global::Xamarin.Auth.Resource.Id.webview = global::Oauth2Demo.Resource.Id.webview;
			global::Xamarin.Auth.Resource.Layout.activity_webview = global::Oauth2Demo.Resource.Layout.activity_webview;
			global::Xamarin.Auth.Resource.String.ApplicationName = global::Oauth2Demo.Resource.String.ApplicationName;
			global::Xamarin.Auth.Resource.String.Hello = global::Oauth2Demo.Resource.String.Hello;
			global::Xamarin.Auth.Resource.String.title_activity_webview = global::Oauth2Demo.Resource.String.title_activity_webview;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_left = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_arrow_back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int buttonAuthenticationh = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int buttonGetSensorData = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int textView1 = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int textViewConsumptionEnergy = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int textViewConsumptionPower = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int textViewGenerationEnergy = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int textViewGenerationPower = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int textViewNetEnergy = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int textViewNetPower = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int textViewStatus = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int webview = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_webview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int title_activity_webview = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
